In [3]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [1]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [2]:
steps=[("standard_scalar",StandardScaler()),
       ("classifier",LogisticRegression())]

In [3]:
steps

[('standard_scalar', StandardScaler()), ('classifier', LogisticRegression())]

In [4]:
pipe=Pipeline(steps)

In [5]:
from sklearn import set_config

In [6]:
set_config(display="diagram")

In [7]:
pipe

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('classifier', LogisticRegression())])

In [8]:
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1500)

In [9]:
X.shape

(1500, 20)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.33, random_state=42)

In [11]:
X_train

array([[ 0.10075261, -0.76836744, -0.0240904 , ...,  1.39661786,
         1.0111608 , -1.05881885],
       [-1.59058264, -2.02171598, -1.16405279, ..., -1.31262627,
        -1.65032944, -0.18299092],
       [-2.46548951, -1.64584946, -0.08630941, ..., -1.3863211 ,
        -0.90387805,  1.5582405 ],
       ...,
       [ 1.32242475,  0.01231882,  0.26395226, ...,  0.08161626,
        -0.51828239, -0.27880973],
       [ 0.56815413, -1.18199797,  1.61676627, ..., -0.972375  ,
        -0.88560077, -1.45814284],
       [ 1.19401109,  0.67955555, -0.23279377, ...,  1.96025086,
         0.35696979,  1.08379553]])

In [12]:
pipe.fit(X_train, y_train)


Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('classifier', LogisticRegression())])

In [13]:
y_pred= pipe.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [14]:
# new program

In [15]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [16]:
steps= [('scaling', StandardScaler()),
        ('PCA', PCA(n_components = 3)),
        ('SVC', SVC())]

In [17]:
pipe2=Pipeline(steps)
pipe2.fit(X_train, y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [18]:
pred = pipe2.predict(X_test)
pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,

In [19]:
from sklearn.impute import SimpleImputer

In [20]:
import numpy as np
numeric_processor=Pipeline(
    steps=[("impute_mean",SimpleImputer(missing_values=np.nan, strategy = 'mean')),
           ('scalar', StandardScaler())])

In [21]:
numeric_processor

Pipeline(steps=[('impute_mean', SimpleImputer()), ('scalar', StandardScaler())])

In [22]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    steps=[("imputation_constant",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehot",OneHotEncoder(handle_unknown="ignore"))]
)

In [23]:
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [24]:
from sklearn.compose import ColumnTransformer

In [25]:
preprocessor = ColumnTransformer(
    [("categorical", categorical_processor,["gender","City"]),
     ("numerical",numeric_processor,["age","height"])])

In [26]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('impute_mean',
                                                  SimpleImputer()),
                                                 ('scalar', StandardScaler())]),
                                 ['age', 'height'])])

In [27]:
from sklearn.pipeline import make_pipeline

In [28]:
pipe= make_pipeline(preprocessor,LogisticRegression())

In [29]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('impute_mean',
                                                                   SimpleImputer()),
                                                                  ('scalar',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])